/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminMigrarLabstateRouteImport } from './routes/admin-migrar-labstate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PendenteRouteImport } from './routes/pendente'
import { Route as RegistroAmostraRouteImport } from './routes/registro-amostra'
import { Route as RegistroChegadaRouteImport } from './routes/registro-chegada'
import { Route as AppAnalisesRouteImport } from './routes/_app.analises'
import { Route as AppAssistenteRouteImport } from './routes/_app.assistente'
import { Route as AppCadastroRouteImport } from './routes/_app.cadastro'
import { Route as AppCadastroDashboardRouteImport } from './routes/_app.cadastro-dashboard'
import { Route as AppChamadasRouteImport } from './routes/_app.chamadas'
import { Route as AppChegadaAmostrasRouteImport } from './routes/_app.chegada-amostras'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEntregasRouteImport } from './routes/_app.entregas'
import { Route as AppEntreguesRouteImport } from './routes/_app.entregues'
import { Route as AppGestaoRouteImport } from './routes/_app.gestao'
import { Route as AppOrdensServicoRouteImport } from './routes/_app.ordens-servico'
import { Route as AppOsAprovadas15dRouteImport } from './routes/_app.os-aprovadas-15d'
import { Route as AppPendentesRouteImport } from './routes/_app.pendentes'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppSaturacaoRouteImport } from './routes/_app.saturacao'
import { Route as AppAdminUsuariosRouteImport } from './routes/_app.admin.usuarios'
import { Route as AppChegadaAmostrasRegistroRouteImport } from './routes/_app.chegada-amostras.registro'
import { Route as AppModelosRelatoriosIndexRouteImport } from './routes/_app.modelos-relatorios.index'
import { Route as AppModelosRelatoriosAdensamentoRouteImport } from './routes/_app.modelos-relatorios.adensamento'
import { Route as AppModelosRelatoriosAsfDapRouteImport } from './routes/_app.modelos-relatorios.asf-dap'
import { Route as AppModelosRelatoriosCisalhamentoDiretoRouteImport } from './routes/_app.modelos-relatorios.cisalhamento-direto'
import { Route as AppModelosRelatoriosCompressaoSimplesRouteImport } from './routes/_app.modelos-relatorios.compressao-simples'
import { Route as AppModelosRelatoriosMespANaturalRouteImport } from './routes/_app.modelos-relatorios.mesp-a-natural'
import { Route as AppModelosRelatoriosModuloResilienciaRouteImport } from './routes/_app.modelos-relatorios.modulo-resiliencia'
import { Route as AppModelosRelatoriosPermVRouteImport } from './routes/_app.modelos-relatorios.perm-v'
import { Route as AppModelosRelatoriosTriaxialCidRouteImport } from './routes/_app.modelos-relatorios.triaxial-cid'
import { Route as AppModelosRelatoriosTriaxialCiuRouteImport } from './routes/_app.modelos-relatorios.triaxial-ciu'
import { Route as AppModelosRelatoriosTriaxialUuRouteImport } from './routes/_app.modelos-relatorios.triaxial-uu'
import { Route as AppModelosRelatoriosUmidadeNaturalRouteImport } from './routes/_app.modelos-relatorios.umidade-natural'
import { Route as AppProgramacaoIndexRouteImport } from './routes/_app.programacao.index'
import { Route as AppProgramacaoCentralRouteImport } from './routes/_app.programacao.central'
import { Route as AppProgramacaoCompatibilidadeRouteImport } from './routes/_app.programacao.compatibilidade'
import { Route as AppProgramacaoDashboardRouteImport } from './routes/_app.programacao.dashboard'
import { Route as AppProgramacaoEquipamentosRouteImport } from './routes/_app.programacao.equipamentos'
import { Route as AppProgramacaoGanttRouteImport } from './routes/_app.programacao.gantt'
import { Route as AppProgramacaoScanRouteImport } from './routes/_app.programacao.scan'
import { Route as AppProgramacaoTiposEnsaioRouteImport } from './routes/_app.programacao.tipos-ensaio'
import { Route as AppRelatorioIndexRouteImport } from './routes/_app.relatorio.index'
import { Route as AppRelatorioAdensamentoRouteImport } from './routes/_app.relatorio.adensamento'
import { Route as AppRelatorioAsfDapRouteImport } from './routes/_app.relatorio.asf-dap'
import { Route as AppRelatorioCisalhamentoDiretoRouteImport } from './routes/_app.relatorio.cisalhamento-direto'
import { Route as AppRelatorioCompressaoSimplesRouteImport } from './routes/_app.relatorio.compressao-simples'
import { Route as AppRelatorioDigitalizacaoRouteImport } from './routes/_app.relatorio.digitalizacao'
import { Route as AppRelatorioEmissoesRouteImport } from './routes/_app.relatorio.emissoes'
import { Route as AppRelatorioMespARouteImport } from './routes/_app.relatorio.mesp-a'
import { Route as AppRelatorioMespANaturalRouteImport } from './routes/_app.relatorio.mesp-a-natural'
import { Route as AppRelatorioModuloResilienciaRouteImport } from './routes/_app.relatorio.modulo-resiliencia'
import { Route as AppRelatorioPendentesRouteImport } from './routes/_app.relatorio.pendentes'
import { Route as AppRelatorioPermVRouteImport } from './routes/_app.relatorio.perm-v'
import { Route as AppRelatorioTriaxialCidRouteImport } from './routes/_app.relatorio.triaxial-cid'
import { Route as AppRelatorioUmidadeNaturalRouteImport } from './routes/_app.relatorio.umidade-natural'
import { Route as ApiPhotoFileIdRouteImport } from './routes/api.photo.$fileId'
import { Route as AppRelatorioDigitalizacaoIndexRouteImport } from './routes/_app.relatorio.digitalizacao.index'
import { Route as AppRelatorioDigitalizacaoAdensamentoRouteImport } from './routes/_app.relatorio.digitalizacao.adensamento'
import { Route as AppRelatorioDigitalizacaoAsfDapRouteImport } from './routes/_app.relatorio.digitalizacao.asf-dap'
import { Route as AppRelatorioDigitalizacaoCapsulasRouteImport } from './routes/_app.relatorio.digitalizacao.capsulas'
import { Route as AppRelatorioDigitalizacaoCompressaoSimplesRouteImport } from './routes/_app.relatorio.digitalizacao.compressao-simples'
import { Route as AppRelatorioDigitalizacaoPendenciasRouteImport } from './routes/_app.relatorio.digitalizacao.pendencias'
import { Route as AppRelatorioDigitalizacaoPermVRouteImport } from './routes/_app.relatorio.digitalizacao.perm-v'
import { Route as AppRelatorioEspeciaisIndexRouteImport } from './routes/_app.relatorio.especiais.index'
import { Route as AppRelatorioEspeciaisOsNumeroRouteImport } from './routes/_app.relatorio.especiais.$osNumero'
import { Route as AppRelatorioOsIndexRouteImport } from './routes/_app.relatorio.os.index'
import { Route as AppRelatorioOsOsIdIndexRouteImport } from './routes/_app.relatorio.os.$osId.index'
import { Route as AppRelatorioOsOsIdAmostraAmostraIdIndexRouteImport } from './routes/_app.relatorio.os.$osId.amostra.$amostraId.index'
import { Route as AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRouteImport } from './routes/_app.relatorio.os.$osId.amostra.$amostraId.ensaio.$ensaioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMigrarLabstateRoute = AdminMigrarLabstateRouteImport.update({
  id: '/admin-migrar-labstate',
  path: '/admin-migrar-labstate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenteRoute = PendenteRouteImport.update({
  id: '/pendente',
  path: '/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroAmostraRoute = RegistroAmostraRouteImport.update({
  id: '/registro-amostra',
  path: '/registro-amostra',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroChegadaRoute = RegistroChegadaRouteImport.update({
  id: '/registro-chegada',
  path: '/registro-chegada',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalisesRoute = AppAnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastroRoute = AppCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastroDashboardRoute = AppCadastroDashboardRouteImport.update({
  id: '/cadastro-dashboard',
  path: '/cadastro-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChamadasRoute = AppChamadasRouteImport.update({
  id: '/chamadas',
  path: '/chamadas',
  getParentRoute: () => AppRoute,
} as any)
const AppChegadaAmostrasRoute = AppChegadaAmostrasRouteImport.update({
  id: '/chegada-amostras',
  path: '/chegada-amostras',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEntregasRoute = AppEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AppRoute,
} as any)
const AppEntreguesRoute = AppEntreguesRouteImport.update({
  id: '/entregues',
  path: '/entregues',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRoute = AppGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensServicoRoute = AppOrdensServicoRouteImport.update({
  id: '/ordens-servico',
  path: '/ordens-servico',
  getParentRoute: () => AppRoute,
} as any)
const AppOsAprovadas15dRoute = AppOsAprovadas15dRouteImport.update({
  id: '/os-aprovadas-15d',
  path: '/os-aprovadas-15d',
  getParentRoute: () => AppRoute,
} as any)
const AppPendentesRoute = AppPendentesRouteImport.update({
  id: '/pendentes',
  path: '/pendentes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppSaturacaoRoute = AppSaturacaoRouteImport.update({
  id: '/saturacao',
  path: '/saturacao',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsuariosRoute = AppAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppChegadaAmostrasRegistroRoute =
  AppChegadaAmostrasRegistroRouteImport.update({
    id: '/registro',
    path: '/registro',
    getParentRoute: () => AppChegadaAmostrasRoute,
  } as any)
const AppModelosRelatoriosIndexRoute =
  AppModelosRelatoriosIndexRouteImport.update({
    id: '/modelos-relatorios/',
    path: '/modelos-relatorios/',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosAdensamentoRoute =
  AppModelosRelatoriosAdensamentoRouteImport.update({
    id: '/modelos-relatorios/adensamento',
    path: '/modelos-relatorios/adensamento',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosAsfDapRoute =
  AppModelosRelatoriosAsfDapRouteImport.update({
    id: '/modelos-relatorios/asf-dap',
    path: '/modelos-relatorios/asf-dap',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosCisalhamentoDiretoRoute =
  AppModelosRelatoriosCisalhamentoDiretoRouteImport.update({
    id: '/modelos-relatorios/cisalhamento-direto',
    path: '/modelos-relatorios/cisalhamento-direto',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosCompressaoSimplesRoute =
  AppModelosRelatoriosCompressaoSimplesRouteImport.update({
    id: '/modelos-relatorios/compressao-simples',
    path: '/modelos-relatorios/compressao-simples',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosMespANaturalRoute =
  AppModelosRelatoriosMespANaturalRouteImport.update({
    id: '/modelos-relatorios/mesp-a-natural',
    path: '/modelos-relatorios/mesp-a-natural',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosModuloResilienciaRoute =
  AppModelosRelatoriosModuloResilienciaRouteImport.update({
    id: '/modelos-relatorios/modulo-resiliencia',
    path: '/modelos-relatorios/modulo-resiliencia',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosPermVRoute =
  AppModelosRelatoriosPermVRouteImport.update({
    id: '/modelos-relatorios/perm-v',
    path: '/modelos-relatorios/perm-v',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosTriaxialCidRoute =
  AppModelosRelatoriosTriaxialCidRouteImport.update({
    id: '/modelos-relatorios/triaxial-cid',
    path: '/modelos-relatorios/triaxial-cid',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosTriaxialCiuRoute =
  AppModelosRelatoriosTriaxialCiuRouteImport.update({
    id: '/modelos-relatorios/triaxial-ciu',
    path: '/modelos-relatorios/triaxial-ciu',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosTriaxialUuRoute =
  AppModelosRelatoriosTriaxialUuRouteImport.update({
    id: '/modelos-relatorios/triaxial-uu',
    path: '/modelos-relatorios/triaxial-uu',
    getParentRoute: () => AppRoute,
  } as any)
const AppModelosRelatoriosUmidadeNaturalRoute =
  AppModelosRelatoriosUmidadeNaturalRouteImport.update({
    id: '/modelos-relatorios/umidade-natural',
    path: '/modelos-relatorios/umidade-natural',
    getParentRoute: () => AppRoute,
  } as any)
const AppProgramacaoIndexRoute = AppProgramacaoIndexRouteImport.update({
  id: '/programacao/',
  path: '/programacao/',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacaoCentralRoute = AppProgramacaoCentralRouteImport.update({
  id: '/programacao/central',
  path: '/programacao/central',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacaoCompatibilidadeRoute =
  AppProgramacaoCompatibilidadeRouteImport.update({
    id: '/programacao/compatibilidade',
    path: '/programacao/compatibilidade',
    getParentRoute: () => AppRoute,
  } as any)
const AppProgramacaoDashboardRoute = AppProgramacaoDashboardRouteImport.update({
  id: '/programacao/dashboard',
  path: '/programacao/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacaoEquipamentosRoute =
  AppProgramacaoEquipamentosRouteImport.update({
    id: '/programacao/equipamentos',
    path: '/programacao/equipamentos',
    getParentRoute: () => AppRoute,
  } as any)
const AppProgramacaoGanttRoute = AppProgramacaoGanttRouteImport.update({
  id: '/programacao/gantt',
  path: '/programacao/gantt',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacaoScanRoute = AppProgramacaoScanRouteImport.update({
  id: '/programacao/scan',
  path: '/programacao/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramacaoTiposEnsaioRoute =
  AppProgramacaoTiposEnsaioRouteImport.update({
    id: '/programacao/tipos-ensaio',
    path: '/programacao/tipos-ensaio',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatorioIndexRoute = AppRelatorioIndexRouteImport.update({
  id: '/relatorio/',
  path: '/relatorio/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioAdensamentoRoute = AppRelatorioAdensamentoRouteImport.update({
  id: '/relatorio/adensamento',
  path: '/relatorio/adensamento',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioAsfDapRoute = AppRelatorioAsfDapRouteImport.update({
  id: '/relatorio/asf-dap',
  path: '/relatorio/asf-dap',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioCisalhamentoDiretoRoute =
  AppRelatorioCisalhamentoDiretoRouteImport.update({
    id: '/relatorio/cisalhamento-direto',
    path: '/relatorio/cisalhamento-direto',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatorioCompressaoSimplesRoute =
  AppRelatorioCompressaoSimplesRouteImport.update({
    id: '/relatorio/compressao-simples',
    path: '/relatorio/compressao-simples',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatorioDigitalizacaoRoute =
  AppRelatorioDigitalizacaoRouteImport.update({
    id: '/relatorio/digitalizacao',
    path: '/relatorio/digitalizacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatorioEmissoesRoute = AppRelatorioEmissoesRouteImport.update({
  id: '/relatorio/emissoes',
  path: '/relatorio/emissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioMespARoute = AppRelatorioMespARouteImport.update({
  id: '/relatorio/mesp-a',
  path: '/relatorio/mesp-a',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioMespANaturalRoute =
  AppRelatorioMespANaturalRouteImport.update({
    id: '/relatorio/mesp-a-natural',
    path: '/relatorio/mesp-a-natural',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatorioModuloResilienciaRoute =
  AppRelatorioModuloResilienciaRouteImport.update({
    id: '/relatorio/modulo-resiliencia',
    path: '/relatorio/modulo-resiliencia',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatorioPendentesRoute = AppRelatorioPendentesRouteImport.update({
  id: '/relatorio/pendentes',
  path: '/relatorio/pendentes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioPermVRoute = AppRelatorioPermVRouteImport.update({
  id: '/relatorio/perm-v',
  path: '/relatorio/perm-v',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioTriaxialCidRoute = AppRelatorioTriaxialCidRouteImport.update({
  id: '/relatorio/triaxial-cid',
  path: '/relatorio/triaxial-cid',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioUmidadeNaturalRoute =
  AppRelatorioUmidadeNaturalRouteImport.update({
    id: '/relatorio/umidade-natural',
    path: '/relatorio/umidade-natural',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPhotoFileIdRoute = ApiPhotoFileIdRouteImport.update({
  id: '/api/photo/$fileId',
  path: '/api/photo/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatorioDigitalizacaoIndexRoute =
  AppRelatorioDigitalizacaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppRelatorioDigitalizacaoRoute,
  } as any)
const AppRelatorioDigitalizacaoAdensamentoRoute =
  AppRelatorioDigitalizacaoAdensamentoRouteImport.update({
    id: '/adensamento',
    path: '/adensamento',
    getParentRoute: () => AppRelatorioDigitalizacaoRoute,
  } as any)
const AppRelatorioDigitalizacaoAsfDapRoute =
  AppRelatorioDigitalizacaoAsfDapRouteImport.update({
    id: '/asf-dap',
    path: '/asf-dap',
    getParentRoute: () => AppRelatorioDigitalizacaoRoute,
  } as any)
const AppRelatorioDigitalizacaoCapsulasRoute =
  AppRelatorioDigitalizacaoCapsulasRouteImport.update({
    id: '/capsulas',
    path: '/capsulas',
    getParentRoute: () => AppRelatorioDigitalizacaoRoute,
  } as any)
const AppRelatorioDigitalizacaoCompressaoSimplesRoute =
  AppRelatorioDigitalizacaoCompressaoSimplesRouteImport.update({
    id: '/compressao-simples',
    path: '/compressao-simples',
    getParentRoute: () => AppRelatorioDigitalizacaoRoute,
  } as any)
const AppRelatorioDigitalizacaoPendenciasRoute =
  AppRelatorioDigitalizacaoPendenciasRouteImport.update({
    id: '/pendencias',
    path: '/pendencias',
    getParentRoute: () => AppRelatorioDigitalizacaoRoute,
  } as any)
const AppRelatorioDigitalizacaoPermVRoute =
  AppRelatorioDigitalizacaoPermVRouteImport.update({
    id: '/perm-v',
    path: '/perm-v',
    getParentRoute: () => AppRelatorioDigitalizacaoRoute,
  } as any)
const AppRelatorioEspeciaisIndexRoute =
  AppRelatorioEspeciaisIndexRouteImport.update({
    id: '/relatorio/especiais/',
    path: '/relatorio/especiais/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatorioEspeciaisOsNumeroRoute =
  AppRelatorioEspeciaisOsNumeroRouteImport.update({
    id: '/relatorio/especiais/$osNumero',
    path: '/relatorio/especiais/$osNumero',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatorioOsIndexRoute = AppRelatorioOsIndexRouteImport.update({
  id: '/relatorio/os/',
  path: '/relatorio/os/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioOsOsIdIndexRoute = AppRelatorioOsOsIdIndexRouteImport.update({
  id: '/relatorio/os/$osId/',
  path: '/relatorio/os/$osId/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioOsOsIdAmostraAmostraIdIndexRoute =
  AppRelatorioOsOsIdAmostraAmostraIdIndexRouteImport.update({
    id: '/relatorio/os/$osId/amostra/$amostraId/',
    path: '/relatorio/os/$osId/amostra/$amostraId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRoute =
  AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRouteImport.update({
    id: '/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId',
    path: '/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-migrar-labstate': typeof AdminMigrarLabstateRoute
  '/auth': typeof AuthRoute
  '/pendente': typeof PendenteRoute
  '/registro-amostra': typeof RegistroAmostraRoute
  '/registro-chegada': typeof RegistroChegadaRoute
  '/analises': typeof AppAnalisesRoute
  '/assistente': typeof AppAssistenteRoute
  '/cadastro': typeof AppCadastroRoute
  '/cadastro-dashboard': typeof AppCadastroDashboardRoute
  '/chamadas': typeof AppChamadasRoute
  '/chegada-amostras': typeof AppChegadaAmostrasRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/entregas': typeof AppEntregasRoute
  '/entregues': typeof AppEntreguesRoute
  '/gestao': typeof AppGestaoRoute
  '/ordens-servico': typeof AppOrdensServicoRoute
  '/os-aprovadas-15d': typeof AppOsAprovadas15dRoute
  '/pendentes': typeof AppPendentesRoute
  '/perfil': typeof AppPerfilRoute
  '/saturacao': typeof AppSaturacaoRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/chegada-amostras/registro': typeof AppChegadaAmostrasRegistroRoute
  '/modelos-relatorios/adensamento': typeof AppModelosRelatoriosAdensamentoRoute
  '/modelos-relatorios/asf-dap': typeof AppModelosRelatoriosAsfDapRoute
  '/modelos-relatorios/cisalhamento-direto': typeof AppModelosRelatoriosCisalhamentoDiretoRoute
  '/modelos-relatorios/compressao-simples': typeof AppModelosRelatoriosCompressaoSimplesRoute
  '/modelos-relatorios/mesp-a-natural': typeof AppModelosRelatoriosMespANaturalRoute
  '/modelos-relatorios/modulo-resiliencia': typeof AppModelosRelatoriosModuloResilienciaRoute
  '/modelos-relatorios/perm-v': typeof AppModelosRelatoriosPermVRoute
  '/modelos-relatorios/triaxial-cid': typeof AppModelosRelatoriosTriaxialCidRoute
  '/modelos-relatorios/triaxial-ciu': typeof AppModelosRelatoriosTriaxialCiuRoute
  '/modelos-relatorios/triaxial-uu': typeof AppModelosRelatoriosTriaxialUuRoute
  '/modelos-relatorios/umidade-natural': typeof AppModelosRelatoriosUmidadeNaturalRoute
  '/programacao/central': typeof AppProgramacaoCentralRoute
  '/programacao/compatibilidade': typeof AppProgramacaoCompatibilidadeRoute
  '/programacao/dashboard': typeof AppProgramacaoDashboardRoute
  '/programacao/equipamentos': typeof AppProgramacaoEquipamentosRoute
  '/programacao/gantt': typeof AppProgramacaoGanttRoute
  '/programacao/scan': typeof AppProgramacaoScanRoute
  '/programacao/tipos-ensaio': typeof AppProgramacaoTiposEnsaioRoute
  '/relatorio/adensamento': typeof AppRelatorioAdensamentoRoute
  '/relatorio/asf-dap': typeof AppRelatorioAsfDapRoute
  '/relatorio/cisalhamento-direto': typeof AppRelatorioCisalhamentoDiretoRoute
  '/relatorio/compressao-simples': typeof AppRelatorioCompressaoSimplesRoute
  '/relatorio/digitalizacao': typeof AppRelatorioDigitalizacaoRouteWithChildren
  '/relatorio/emissoes': typeof AppRelatorioEmissoesRoute
  '/relatorio/mesp-a': typeof AppRelatorioMespARoute
  '/relatorio/mesp-a-natural': typeof AppRelatorioMespANaturalRoute
  '/relatorio/modulo-resiliencia': typeof AppRelatorioModuloResilienciaRoute
  '/relatorio/pendentes': typeof AppRelatorioPendentesRoute
  '/relatorio/perm-v': typeof AppRelatorioPermVRoute
  '/relatorio/triaxial-cid': typeof AppRelatorioTriaxialCidRoute
  '/relatorio/umidade-natural': typeof AppRelatorioUmidadeNaturalRoute
  '/api/photo/$fileId': typeof ApiPhotoFileIdRoute
  '/modelos-relatorios/': typeof AppModelosRelatoriosIndexRoute
  '/programacao/': typeof AppProgramacaoIndexRoute
  '/relatorio/': typeof AppRelatorioIndexRoute
  '/relatorio/digitalizacao/adensamento': typeof AppRelatorioDigitalizacaoAdensamentoRoute
  '/relatorio/digitalizacao/asf-dap': typeof AppRelatorioDigitalizacaoAsfDapRoute
  '/relatorio/digitalizacao/capsulas': typeof AppRelatorioDigitalizacaoCapsulasRoute
  '/relatorio/digitalizacao/compressao-simples': typeof AppRelatorioDigitalizacaoCompressaoSimplesRoute
  '/relatorio/digitalizacao/pendencias': typeof AppRelatorioDigitalizacaoPendenciasRoute
  '/relatorio/digitalizacao/perm-v': typeof AppRelatorioDigitalizacaoPermVRoute
  '/relatorio/especiais/$osNumero': typeof AppRelatorioEspeciaisOsNumeroRoute
  '/relatorio/digitalizacao/': typeof AppRelatorioDigitalizacaoIndexRoute
  '/relatorio/especiais/': typeof AppRelatorioEspeciaisIndexRoute
  '/relatorio/os/': typeof AppRelatorioOsIndexRoute
  '/relatorio/os/$osId/': typeof AppRelatorioOsOsIdIndexRoute
  '/relatorio/os/$osId/amostra/$amostraId/': typeof AppRelatorioOsOsIdAmostraAmostraIdIndexRoute
  '/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId': typeof AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-migrar-labstate': typeof AdminMigrarLabstateRoute
  '/auth': typeof AuthRoute
  '/pendente': typeof PendenteRoute
  '/registro-amostra': typeof RegistroAmostraRoute
  '/registro-chegada': typeof RegistroChegadaRoute
  '/analises': typeof AppAnalisesRoute
  '/assistente': typeof AppAssistenteRoute
  '/cadastro': typeof AppCadastroRoute
  '/cadastro-dashboard': typeof AppCadastroDashboardRoute
  '/chamadas': typeof AppChamadasRoute
  '/chegada-amostras': typeof AppChegadaAmostrasRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/entregas': typeof AppEntregasRoute
  '/entregues': typeof AppEntreguesRoute
  '/gestao': typeof AppGestaoRoute
  '/ordens-servico': typeof AppOrdensServicoRoute
  '/os-aprovadas-15d': typeof AppOsAprovadas15dRoute
  '/pendentes': typeof AppPendentesRoute
  '/perfil': typeof AppPerfilRoute
  '/saturacao': typeof AppSaturacaoRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/chegada-amostras/registro': typeof AppChegadaAmostrasRegistroRoute
  '/modelos-relatorios/adensamento': typeof AppModelosRelatoriosAdensamentoRoute
  '/modelos-relatorios/asf-dap': typeof AppModelosRelatoriosAsfDapRoute
  '/modelos-relatorios/cisalhamento-direto': typeof AppModelosRelatoriosCisalhamentoDiretoRoute
  '/modelos-relatorios/compressao-simples': typeof AppModelosRelatoriosCompressaoSimplesRoute
  '/modelos-relatorios/mesp-a-natural': typeof AppModelosRelatoriosMespANaturalRoute
  '/modelos-relatorios/modulo-resiliencia': typeof AppModelosRelatoriosModuloResilienciaRoute
  '/modelos-relatorios/perm-v': typeof AppModelosRelatoriosPermVRoute
  '/modelos-relatorios/triaxial-cid': typeof AppModelosRelatoriosTriaxialCidRoute
  '/modelos-relatorios/triaxial-ciu': typeof AppModelosRelatoriosTriaxialCiuRoute
  '/modelos-relatorios/triaxial-uu': typeof AppModelosRelatoriosTriaxialUuRoute
  '/modelos-relatorios/umidade-natural': typeof AppModelosRelatoriosUmidadeNaturalRoute
  '/programacao/central': typeof AppProgramacaoCentralRoute
  '/programacao/compatibilidade': typeof AppProgramacaoCompatibilidadeRoute
  '/programacao/dashboard': typeof AppProgramacaoDashboardRoute
  '/programacao/equipamentos': typeof AppProgramacaoEquipamentosRoute
  '/programacao/gantt': typeof AppProgramacaoGanttRoute
  '/programacao/scan': typeof AppProgramacaoScanRoute
  '/programacao/tipos-ensaio': typeof AppProgramacaoTiposEnsaioRoute
  '/relatorio/adensamento': typeof AppRelatorioAdensamentoRoute
  '/relatorio/asf-dap': typeof AppRelatorioAsfDapRoute
  '/relatorio/cisalhamento-direto': typeof AppRelatorioCisalhamentoDiretoRoute
  '/relatorio/compressao-simples': typeof AppRelatorioCompressaoSimplesRoute
  '/relatorio/emissoes': typeof AppRelatorioEmissoesRoute
  '/relatorio/mesp-a': typeof AppRelatorioMespARoute
  '/relatorio/mesp-a-natural': typeof AppRelatorioMespANaturalRoute
  '/relatorio/modulo-resiliencia': typeof AppRelatorioModuloResilienciaRoute
  '/relatorio/pendentes': typeof AppRelatorioPendentesRoute
  '/relatorio/perm-v': typeof AppRelatorioPermVRoute
  '/relatorio/triaxial-cid': typeof AppRelatorioTriaxialCidRoute
  '/relatorio/umidade-natural': typeof AppRelatorioUmidadeNaturalRoute
  '/api/photo/$fileId': typeof ApiPhotoFileIdRoute
  '/modelos-relatorios': typeof AppModelosRelatoriosIndexRoute
  '/programacao': typeof AppProgramacaoIndexRoute
  '/relatorio': typeof AppRelatorioIndexRoute
  '/relatorio/digitalizacao/adensamento': typeof AppRelatorioDigitalizacaoAdensamentoRoute
  '/relatorio/digitalizacao/asf-dap': typeof AppRelatorioDigitalizacaoAsfDapRoute
  '/relatorio/digitalizacao/capsulas': typeof AppRelatorioDigitalizacaoCapsulasRoute
  '/relatorio/digitalizacao/compressao-simples': typeof AppRelatorioDigitalizacaoCompressaoSimplesRoute
  '/relatorio/digitalizacao/pendencias': typeof AppRelatorioDigitalizacaoPendenciasRoute
  '/relatorio/digitalizacao/perm-v': typeof AppRelatorioDigitalizacaoPermVRoute
  '/relatorio/especiais/$osNumero': typeof AppRelatorioEspeciaisOsNumeroRoute
  '/relatorio/digitalizacao': typeof AppRelatorioDigitalizacaoIndexRoute
  '/relatorio/especiais': typeof AppRelatorioEspeciaisIndexRoute
  '/relatorio/os': typeof AppRelatorioOsIndexRoute
  '/relatorio/os/$osId': typeof AppRelatorioOsOsIdIndexRoute
  '/relatorio/os/$osId/amostra/$amostraId': typeof AppRelatorioOsOsIdAmostraAmostraIdIndexRoute
  '/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId': typeof AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin-migrar-labstate': typeof AdminMigrarLabstateRoute
  '/auth': typeof AuthRoute
  '/pendente': typeof PendenteRoute
  '/registro-amostra': typeof RegistroAmostraRoute
  '/registro-chegada': typeof RegistroChegadaRoute
  '/_app/analises': typeof AppAnalisesRoute
  '/_app/assistente': typeof AppAssistenteRoute
  '/_app/cadastro': typeof AppCadastroRoute
  '/_app/cadastro-dashboard': typeof AppCadastroDashboardRoute
  '/_app/chamadas': typeof AppChamadasRoute
  '/_app/chegada-amostras': typeof AppChegadaAmostrasRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/entregas': typeof AppEntregasRoute
  '/_app/entregues': typeof AppEntreguesRoute
  '/_app/gestao': typeof AppGestaoRoute
  '/_app/ordens-servico': typeof AppOrdensServicoRoute
  '/_app/os-aprovadas-15d': typeof AppOsAprovadas15dRoute
  '/_app/pendentes': typeof AppPendentesRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/saturacao': typeof AppSaturacaoRoute
  '/_app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/_app/chegada-amostras/registro': typeof AppChegadaAmostrasRegistroRoute
  '/_app/modelos-relatorios/adensamento': typeof AppModelosRelatoriosAdensamentoRoute
  '/_app/modelos-relatorios/asf-dap': typeof AppModelosRelatoriosAsfDapRoute
  '/_app/modelos-relatorios/cisalhamento-direto': typeof AppModelosRelatoriosCisalhamentoDiretoRoute
  '/_app/modelos-relatorios/compressao-simples': typeof AppModelosRelatoriosCompressaoSimplesRoute
  '/_app/modelos-relatorios/mesp-a-natural': typeof AppModelosRelatoriosMespANaturalRoute
  '/_app/modelos-relatorios/modulo-resiliencia': typeof AppModelosRelatoriosModuloResilienciaRoute
  '/_app/modelos-relatorios/perm-v': typeof AppModelosRelatoriosPermVRoute
  '/_app/modelos-relatorios/triaxial-cid': typeof AppModelosRelatoriosTriaxialCidRoute
  '/_app/modelos-relatorios/triaxial-ciu': typeof AppModelosRelatoriosTriaxialCiuRoute
  '/_app/modelos-relatorios/triaxial-uu': typeof AppModelosRelatoriosTriaxialUuRoute
  '/_app/modelos-relatorios/umidade-natural': typeof AppModelosRelatoriosUmidadeNaturalRoute
  '/_app/programacao/central': typeof AppProgramacaoCentralRoute
  '/_app/programacao/compatibilidade': typeof AppProgramacaoCompatibilidadeRoute
  '/_app/programacao/dashboard': typeof AppProgramacaoDashboardRoute
  '/_app/programacao/equipamentos': typeof AppProgramacaoEquipamentosRoute
  '/_app/programacao/gantt': typeof AppProgramacaoGanttRoute
  '/_app/programacao/scan': typeof AppProgramacaoScanRoute
  '/_app/programacao/tipos-ensaio': typeof AppProgramacaoTiposEnsaioRoute
  '/_app/relatorio/adensamento': typeof AppRelatorioAdensamentoRoute
  '/_app/relatorio/asf-dap': typeof AppRelatorioAsfDapRoute
  '/_app/relatorio/cisalhamento-direto': typeof AppRelatorioCisalhamentoDiretoRoute
  '/_app/relatorio/compressao-simples': typeof AppRelatorioCompressaoSimplesRoute
  '/_app/relatorio/digitalizacao': typeof AppRelatorioDigitalizacaoRouteWithChildren
  '/_app/relatorio/emissoes': typeof AppRelatorioEmissoesRoute
  '/_app/relatorio/mesp-a': typeof AppRelatorioMespARoute
  '/_app/relatorio/mesp-a-natural': typeof AppRelatorioMespANaturalRoute
  '/_app/relatorio/modulo-resiliencia': typeof AppRelatorioModuloResilienciaRoute
  '/_app/relatorio/pendentes': typeof AppRelatorioPendentesRoute
  '/_app/relatorio/perm-v': typeof AppRelatorioPermVRoute
  '/_app/relatorio/triaxial-cid': typeof AppRelatorioTriaxialCidRoute
  '/_app/relatorio/umidade-natural': typeof AppRelatorioUmidadeNaturalRoute
  '/api/photo/$fileId': typeof ApiPhotoFileIdRoute
  '/_app/modelos-relatorios/': typeof AppModelosRelatoriosIndexRoute
  '/_app/programacao/': typeof AppProgramacaoIndexRoute
  '/_app/relatorio/': typeof AppRelatorioIndexRoute
  '/_app/relatorio/digitalizacao/adensamento': typeof AppRelatorioDigitalizacaoAdensamentoRoute
  '/_app/relatorio/digitalizacao/asf-dap': typeof AppRelatorioDigitalizacaoAsfDapRoute
  '/_app/relatorio/digitalizacao/capsulas': typeof AppRelatorioDigitalizacaoCapsulasRoute
  '/_app/relatorio/digitalizacao/compressao-simples': typeof AppRelatorioDigitalizacaoCompressaoSimplesRoute
  '/_app/relatorio/digitalizacao/pendencias': typeof AppRelatorioDigitalizacaoPendenciasRoute
  '/_app/relatorio/digitalizacao/perm-v': typeof AppRelatorioDigitalizacaoPermVRoute
  '/_app/relatorio/especiais/$osNumero': typeof AppRelatorioEspeciaisOsNumeroRoute
  '/_app/relatorio/digitalizacao/': typeof AppRelatorioDigitalizacaoIndexRoute
  '/_app/relatorio/especiais/': typeof AppRelatorioEspeciaisIndexRoute
  '/_app/relatorio/os/': typeof AppRelatorioOsIndexRoute
  '/_app/relatorio/os/$osId/': typeof AppRelatorioOsOsIdIndexRoute
  '/_app/relatorio/os/$osId/amostra/$amostraId/': typeof AppRelatorioOsOsIdAmostraAmostraIdIndexRoute
  '/_app/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId': typeof AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-migrar-labstate'
    | '/auth'
    | '/pendente'
    | '/registro-amostra'
    | '/registro-chegada'
    | '/analises'
    | '/assistente'
    | '/cadastro'
    | '/cadastro-dashboard'
    | '/chamadas'
    | '/chegada-amostras'
    | '/dashboard'
    | '/entregas'
    | '/entregues'
    | '/gestao'
    | '/ordens-servico'
    | '/os-aprovadas-15d'
    | '/pendentes'
    | '/perfil'
    | '/saturacao'
    | '/admin/usuarios'
    | '/chegada-amostras/registro'
    | '/modelos-relatorios/adensamento'
    | '/modelos-relatorios/asf-dap'
    | '/modelos-relatorios/cisalhamento-direto'
    | '/modelos-relatorios/compressao-simples'
    | '/modelos-relatorios/mesp-a-natural'
    | '/modelos-relatorios/modulo-resiliencia'
    | '/modelos-relatorios/perm-v'
    | '/modelos-relatorios/triaxial-cid'
    | '/modelos-relatorios/triaxial-ciu'
    | '/modelos-relatorios/triaxial-uu'
    | '/modelos-relatorios/umidade-natural'
    | '/programacao/central'
    | '/programacao/compatibilidade'
    | '/programacao/dashboard'
    | '/programacao/equipamentos'
    | '/programacao/gantt'
    | '/programacao/scan'
    | '/programacao/tipos-ensaio'
    | '/relatorio/adensamento'
    | '/relatorio/asf-dap'
    | '/relatorio/cisalhamento-direto'
    | '/relatorio/compressao-simples'
    | '/relatorio/digitalizacao'
    | '/relatorio/emissoes'
    | '/relatorio/mesp-a'
    | '/relatorio/mesp-a-natural'
    | '/relatorio/modulo-resiliencia'
    | '/relatorio/pendentes'
    | '/relatorio/perm-v'
    | '/relatorio/triaxial-cid'
    | '/relatorio/umidade-natural'
    | '/api/photo/$fileId'
    | '/modelos-relatorios/'
    | '/programacao/'
    | '/relatorio/'
    | '/relatorio/digitalizacao/adensamento'
    | '/relatorio/digitalizacao/asf-dap'
    | '/relatorio/digitalizacao/capsulas'
    | '/relatorio/digitalizacao/compressao-simples'
    | '/relatorio/digitalizacao/pendencias'
    | '/relatorio/digitalizacao/perm-v'
    | '/relatorio/especiais/$osNumero'
    | '/relatorio/digitalizacao/'
    | '/relatorio/especiais/'
    | '/relatorio/os/'
    | '/relatorio/os/$osId/'
    | '/relatorio/os/$osId/amostra/$amostraId/'
    | '/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-migrar-labstate'
    | '/auth'
    | '/pendente'
    | '/registro-amostra'
    | '/registro-chegada'
    | '/analises'
    | '/assistente'
    | '/cadastro'
    | '/cadastro-dashboard'
    | '/chamadas'
    | '/chegada-amostras'
    | '/dashboard'
    | '/entregas'
    | '/entregues'
    | '/gestao'
    | '/ordens-servico'
    | '/os-aprovadas-15d'
    | '/pendentes'
    | '/perfil'
    | '/saturacao'
    | '/admin/usuarios'
    | '/chegada-amostras/registro'
    | '/modelos-relatorios/adensamento'
    | '/modelos-relatorios/asf-dap'
    | '/modelos-relatorios/cisalhamento-direto'
    | '/modelos-relatorios/compressao-simples'
    | '/modelos-relatorios/mesp-a-natural'
    | '/modelos-relatorios/modulo-resiliencia'
    | '/modelos-relatorios/perm-v'
    | '/modelos-relatorios/triaxial-cid'
    | '/modelos-relatorios/triaxial-ciu'
    | '/modelos-relatorios/triaxial-uu'
    | '/modelos-relatorios/umidade-natural'
    | '/programacao/central'
    | '/programacao/compatibilidade'
    | '/programacao/dashboard'
    | '/programacao/equipamentos'
    | '/programacao/gantt'
    | '/programacao/scan'
    | '/programacao/tipos-ensaio'
    | '/relatorio/adensamento'
    | '/relatorio/asf-dap'
    | '/relatorio/cisalhamento-direto'
    | '/relatorio/compressao-simples'
    | '/relatorio/emissoes'
    | '/relatorio/mesp-a'
    | '/relatorio/mesp-a-natural'
    | '/relatorio/modulo-resiliencia'
    | '/relatorio/pendentes'
    | '/relatorio/perm-v'
    | '/relatorio/triaxial-cid'
    | '/relatorio/umidade-natural'
    | '/api/photo/$fileId'
    | '/modelos-relatorios'
    | '/programacao'
    | '/relatorio'
    | '/relatorio/digitalizacao/adensamento'
    | '/relatorio/digitalizacao/asf-dap'
    | '/relatorio/digitalizacao/capsulas'
    | '/relatorio/digitalizacao/compressao-simples'
    | '/relatorio/digitalizacao/pendencias'
    | '/relatorio/digitalizacao/perm-v'
    | '/relatorio/especiais/$osNumero'
    | '/relatorio/digitalizacao'
    | '/relatorio/especiais'
    | '/relatorio/os'
    | '/relatorio/os/$osId'
    | '/relatorio/os/$osId/amostra/$amostraId'
    | '/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin-migrar-labstate'
    | '/auth'
    | '/pendente'
    | '/registro-amostra'
    | '/registro-chegada'
    | '/_app/analises'
    | '/_app/assistente'
    | '/_app/cadastro'
    | '/_app/cadastro-dashboard'
    | '/_app/chamadas'
    | '/_app/chegada-amostras'
    | '/_app/dashboard'
    | '/_app/entregas'
    | '/_app/entregues'
    | '/_app/gestao'
    | '/_app/ordens-servico'
    | '/_app/os-aprovadas-15d'
    | '/_app/pendentes'
    | '/_app/perfil'
    | '/_app/saturacao'
    | '/_app/admin/usuarios'
    | '/_app/chegada-amostras/registro'
    | '/_app/modelos-relatorios/adensamento'
    | '/_app/modelos-relatorios/asf-dap'
    | '/_app/modelos-relatorios/cisalhamento-direto'
    | '/_app/modelos-relatorios/compressao-simples'
    | '/_app/modelos-relatorios/mesp-a-natural'
    | '/_app/modelos-relatorios/modulo-resiliencia'
    | '/_app/modelos-relatorios/perm-v'
    | '/_app/modelos-relatorios/triaxial-cid'
    | '/_app/modelos-relatorios/triaxial-ciu'
    | '/_app/modelos-relatorios/triaxial-uu'
    | '/_app/modelos-relatorios/umidade-natural'
    | '/_app/programacao/central'
    | '/_app/programacao/compatibilidade'
    | '/_app/programacao/dashboard'
    | '/_app/programacao/equipamentos'
    | '/_app/programacao/gantt'
    | '/_app/programacao/scan'
    | '/_app/programacao/tipos-ensaio'
    | '/_app/relatorio/adensamento'
    | '/_app/relatorio/asf-dap'
    | '/_app/relatorio/cisalhamento-direto'
    | '/_app/relatorio/compressao-simples'
    | '/_app/relatorio/digitalizacao'
    | '/_app/relatorio/emissoes'
    | '/_app/relatorio/mesp-a'
    | '/_app/relatorio/mesp-a-natural'
    | '/_app/relatorio/modulo-resiliencia'
    | '/_app/relatorio/pendentes'
    | '/_app/relatorio/perm-v'
    | '/_app/relatorio/triaxial-cid'
    | '/_app/relatorio/umidade-natural'
    | '/api/photo/$fileId'
    | '/_app/modelos-relatorios/'
    | '/_app/programacao/'
    | '/_app/relatorio/'
    | '/_app/relatorio/digitalizacao/adensamento'
    | '/_app/relatorio/digitalizacao/asf-dap'
    | '/_app/relatorio/digitalizacao/capsulas'
    | '/_app/relatorio/digitalizacao/compressao-simples'
    | '/_app/relatorio/digitalizacao/pendencias'
    | '/_app/relatorio/digitalizacao/perm-v'
    | '/_app/relatorio/especiais/$osNumero'
    | '/_app/relatorio/digitalizacao/'
    | '/_app/relatorio/especiais/'
    | '/_app/relatorio/os/'
    | '/_app/relatorio/os/$osId/'
    | '/_app/relatorio/os/$osId/amostra/$amostraId/'
    | '/_app/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminMigrarLabstateRoute: typeof AdminMigrarLabstateRoute
  AuthRoute: typeof AuthRoute
  PendenteRoute: typeof PendenteRoute
  RegistroAmostraRoute: typeof RegistroAmostraRoute
  RegistroChegadaRoute: typeof RegistroChegadaRoute
  ApiPhotoFileIdRoute: typeof ApiPhotoFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-migrar-labstate': {
      id: '/admin-migrar-labstate'
      path: '/admin-migrar-labstate'
      fullPath: '/admin-migrar-labstate'
      preLoaderRoute: typeof AdminMigrarLabstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendente': {
      id: '/pendente'
      path: '/pendente'
      fullPath: '/pendente'
      preLoaderRoute: typeof PendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro-amostra': {
      id: '/registro-amostra'
      path: '/registro-amostra'
      fullPath: '/registro-amostra'
      preLoaderRoute: typeof RegistroAmostraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro-chegada': {
      id: '/registro-chegada'
      path: '/registro-chegada'
      fullPath: '/registro-chegada'
      preLoaderRoute: typeof RegistroChegadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analises': {
      id: '/_app/analises'
      path: '/analises'
      fullPath: '/analises'
      preLoaderRoute: typeof AppAnalisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistente': {
      id: '/_app/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastro': {
      id: '/_app/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AppCadastroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastro-dashboard': {
      id: '/_app/cadastro-dashboard'
      path: '/cadastro-dashboard'
      fullPath: '/cadastro-dashboard'
      preLoaderRoute: typeof AppCadastroDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chamadas': {
      id: '/_app/chamadas'
      path: '/chamadas'
      fullPath: '/chamadas'
      preLoaderRoute: typeof AppChamadasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chegada-amostras': {
      id: '/_app/chegada-amostras'
      path: '/chegada-amostras'
      fullPath: '/chegada-amostras'
      preLoaderRoute: typeof AppChegadaAmostrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entregas': {
      id: '/_app/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AppEntregasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entregues': {
      id: '/_app/entregues'
      path: '/entregues'
      fullPath: '/entregues'
      preLoaderRoute: typeof AppEntreguesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestao': {
      id: '/_app/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AppGestaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens-servico': {
      id: '/_app/ordens-servico'
      path: '/ordens-servico'
      fullPath: '/ordens-servico'
      preLoaderRoute: typeof AppOrdensServicoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/os-aprovadas-15d': {
      id: '/_app/os-aprovadas-15d'
      path: '/os-aprovadas-15d'
      fullPath: '/os-aprovadas-15d'
      preLoaderRoute: typeof AppOsAprovadas15dRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pendentes': {
      id: '/_app/pendentes'
      path: '/pendentes'
      fullPath: '/pendentes'
      preLoaderRoute: typeof AppPendentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturacao': {
      id: '/_app/saturacao'
      path: '/saturacao'
      fullPath: '/saturacao'
      preLoaderRoute: typeof AppSaturacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/usuarios': {
      id: '/_app/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AppAdminUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chegada-amostras/registro': {
      id: '/_app/chegada-amostras/registro'
      path: '/registro'
      fullPath: '/chegada-amostras/registro'
      preLoaderRoute: typeof AppChegadaAmostrasRegistroRouteImport
      parentRoute: typeof AppChegadaAmostrasRoute
    }
    '/_app/modelos-relatorios/': {
      id: '/_app/modelos-relatorios/'
      path: '/modelos-relatorios'
      fullPath: '/modelos-relatorios/'
      preLoaderRoute: typeof AppModelosRelatoriosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/adensamento': {
      id: '/_app/modelos-relatorios/adensamento'
      path: '/modelos-relatorios/adensamento'
      fullPath: '/modelos-relatorios/adensamento'
      preLoaderRoute: typeof AppModelosRelatoriosAdensamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/asf-dap': {
      id: '/_app/modelos-relatorios/asf-dap'
      path: '/modelos-relatorios/asf-dap'
      fullPath: '/modelos-relatorios/asf-dap'
      preLoaderRoute: typeof AppModelosRelatoriosAsfDapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/cisalhamento-direto': {
      id: '/_app/modelos-relatorios/cisalhamento-direto'
      path: '/modelos-relatorios/cisalhamento-direto'
      fullPath: '/modelos-relatorios/cisalhamento-direto'
      preLoaderRoute: typeof AppModelosRelatoriosCisalhamentoDiretoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/compressao-simples': {
      id: '/_app/modelos-relatorios/compressao-simples'
      path: '/modelos-relatorios/compressao-simples'
      fullPath: '/modelos-relatorios/compressao-simples'
      preLoaderRoute: typeof AppModelosRelatoriosCompressaoSimplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/mesp-a-natural': {
      id: '/_app/modelos-relatorios/mesp-a-natural'
      path: '/modelos-relatorios/mesp-a-natural'
      fullPath: '/modelos-relatorios/mesp-a-natural'
      preLoaderRoute: typeof AppModelosRelatoriosMespANaturalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/modulo-resiliencia': {
      id: '/_app/modelos-relatorios/modulo-resiliencia'
      path: '/modelos-relatorios/modulo-resiliencia'
      fullPath: '/modelos-relatorios/modulo-resiliencia'
      preLoaderRoute: typeof AppModelosRelatoriosModuloResilienciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/perm-v': {
      id: '/_app/modelos-relatorios/perm-v'
      path: '/modelos-relatorios/perm-v'
      fullPath: '/modelos-relatorios/perm-v'
      preLoaderRoute: typeof AppModelosRelatoriosPermVRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/triaxial-cid': {
      id: '/_app/modelos-relatorios/triaxial-cid'
      path: '/modelos-relatorios/triaxial-cid'
      fullPath: '/modelos-relatorios/triaxial-cid'
      preLoaderRoute: typeof AppModelosRelatoriosTriaxialCidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/triaxial-ciu': {
      id: '/_app/modelos-relatorios/triaxial-ciu'
      path: '/modelos-relatorios/triaxial-ciu'
      fullPath: '/modelos-relatorios/triaxial-ciu'
      preLoaderRoute: typeof AppModelosRelatoriosTriaxialCiuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/triaxial-uu': {
      id: '/_app/modelos-relatorios/triaxial-uu'
      path: '/modelos-relatorios/triaxial-uu'
      fullPath: '/modelos-relatorios/triaxial-uu'
      preLoaderRoute: typeof AppModelosRelatoriosTriaxialUuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modelos-relatorios/umidade-natural': {
      id: '/_app/modelos-relatorios/umidade-natural'
      path: '/modelos-relatorios/umidade-natural'
      fullPath: '/modelos-relatorios/umidade-natural'
      preLoaderRoute: typeof AppModelosRelatoriosUmidadeNaturalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao/': {
      id: '/_app/programacao/'
      path: '/programacao'
      fullPath: '/programacao/'
      preLoaderRoute: typeof AppProgramacaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao/central': {
      id: '/_app/programacao/central'
      path: '/programacao/central'
      fullPath: '/programacao/central'
      preLoaderRoute: typeof AppProgramacaoCentralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao/compatibilidade': {
      id: '/_app/programacao/compatibilidade'
      path: '/programacao/compatibilidade'
      fullPath: '/programacao/compatibilidade'
      preLoaderRoute: typeof AppProgramacaoCompatibilidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao/dashboard': {
      id: '/_app/programacao/dashboard'
      path: '/programacao/dashboard'
      fullPath: '/programacao/dashboard'
      preLoaderRoute: typeof AppProgramacaoDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao/equipamentos': {
      id: '/_app/programacao/equipamentos'
      path: '/programacao/equipamentos'
      fullPath: '/programacao/equipamentos'
      preLoaderRoute: typeof AppProgramacaoEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao/gantt': {
      id: '/_app/programacao/gantt'
      path: '/programacao/gantt'
      fullPath: '/programacao/gantt'
      preLoaderRoute: typeof AppProgramacaoGanttRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao/scan': {
      id: '/_app/programacao/scan'
      path: '/programacao/scan'
      fullPath: '/programacao/scan'
      preLoaderRoute: typeof AppProgramacaoScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programacao/tipos-ensaio': {
      id: '/_app/programacao/tipos-ensaio'
      path: '/programacao/tipos-ensaio'
      fullPath: '/programacao/tipos-ensaio'
      preLoaderRoute: typeof AppProgramacaoTiposEnsaioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/': {
      id: '/_app/relatorio/'
      path: '/relatorio'
      fullPath: '/relatorio/'
      preLoaderRoute: typeof AppRelatorioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/adensamento': {
      id: '/_app/relatorio/adensamento'
      path: '/relatorio/adensamento'
      fullPath: '/relatorio/adensamento'
      preLoaderRoute: typeof AppRelatorioAdensamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/asf-dap': {
      id: '/_app/relatorio/asf-dap'
      path: '/relatorio/asf-dap'
      fullPath: '/relatorio/asf-dap'
      preLoaderRoute: typeof AppRelatorioAsfDapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/cisalhamento-direto': {
      id: '/_app/relatorio/cisalhamento-direto'
      path: '/relatorio/cisalhamento-direto'
      fullPath: '/relatorio/cisalhamento-direto'
      preLoaderRoute: typeof AppRelatorioCisalhamentoDiretoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/compressao-simples': {
      id: '/_app/relatorio/compressao-simples'
      path: '/relatorio/compressao-simples'
      fullPath: '/relatorio/compressao-simples'
      preLoaderRoute: typeof AppRelatorioCompressaoSimplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/digitalizacao': {
      id: '/_app/relatorio/digitalizacao'
      path: '/relatorio/digitalizacao'
      fullPath: '/relatorio/digitalizacao'
      preLoaderRoute: typeof AppRelatorioDigitalizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/emissoes': {
      id: '/_app/relatorio/emissoes'
      path: '/relatorio/emissoes'
      fullPath: '/relatorio/emissoes'
      preLoaderRoute: typeof AppRelatorioEmissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/mesp-a': {
      id: '/_app/relatorio/mesp-a'
      path: '/relatorio/mesp-a'
      fullPath: '/relatorio/mesp-a'
      preLoaderRoute: typeof AppRelatorioMespARouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/mesp-a-natural': {
      id: '/_app/relatorio/mesp-a-natural'
      path: '/relatorio/mesp-a-natural'
      fullPath: '/relatorio/mesp-a-natural'
      preLoaderRoute: typeof AppRelatorioMespANaturalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/modulo-resiliencia': {
      id: '/_app/relatorio/modulo-resiliencia'
      path: '/relatorio/modulo-resiliencia'
      fullPath: '/relatorio/modulo-resiliencia'
      preLoaderRoute: typeof AppRelatorioModuloResilienciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/pendentes': {
      id: '/_app/relatorio/pendentes'
      path: '/relatorio/pendentes'
      fullPath: '/relatorio/pendentes'
      preLoaderRoute: typeof AppRelatorioPendentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/perm-v': {
      id: '/_app/relatorio/perm-v'
      path: '/relatorio/perm-v'
      fullPath: '/relatorio/perm-v'
      preLoaderRoute: typeof AppRelatorioPermVRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/triaxial-cid': {
      id: '/_app/relatorio/triaxial-cid'
      path: '/relatorio/triaxial-cid'
      fullPath: '/relatorio/triaxial-cid'
      preLoaderRoute: typeof AppRelatorioTriaxialCidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/umidade-natural': {
      id: '/_app/relatorio/umidade-natural'
      path: '/relatorio/umidade-natural'
      fullPath: '/relatorio/umidade-natural'
      preLoaderRoute: typeof AppRelatorioUmidadeNaturalRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/photo/$fileId': {
      id: '/api/photo/$fileId'
      path: '/api/photo/$fileId'
      fullPath: '/api/photo/$fileId'
      preLoaderRoute: typeof ApiPhotoFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorio/digitalizacao/': {
      id: '/_app/relatorio/digitalizacao/'
      path: '/'
      fullPath: '/relatorio/digitalizacao/'
      preLoaderRoute: typeof AppRelatorioDigitalizacaoIndexRouteImport
      parentRoute: typeof AppRelatorioDigitalizacaoRoute
    }
    '/_app/relatorio/digitalizacao/adensamento': {
      id: '/_app/relatorio/digitalizacao/adensamento'
      path: '/adensamento'
      fullPath: '/relatorio/digitalizacao/adensamento'
      preLoaderRoute: typeof AppRelatorioDigitalizacaoAdensamentoRouteImport
      parentRoute: typeof AppRelatorioDigitalizacaoRoute
    }
    '/_app/relatorio/digitalizacao/asf-dap': {
      id: '/_app/relatorio/digitalizacao/asf-dap'
      path: '/asf-dap'
      fullPath: '/relatorio/digitalizacao/asf-dap'
      preLoaderRoute: typeof AppRelatorioDigitalizacaoAsfDapRouteImport
      parentRoute: typeof AppRelatorioDigitalizacaoRoute
    }
    '/_app/relatorio/digitalizacao/capsulas': {
      id: '/_app/relatorio/digitalizacao/capsulas'
      path: '/capsulas'
      fullPath: '/relatorio/digitalizacao/capsulas'
      preLoaderRoute: typeof AppRelatorioDigitalizacaoCapsulasRouteImport
      parentRoute: typeof AppRelatorioDigitalizacaoRoute
    }
    '/_app/relatorio/digitalizacao/compressao-simples': {
      id: '/_app/relatorio/digitalizacao/compressao-simples'
      path: '/compressao-simples'
      fullPath: '/relatorio/digitalizacao/compressao-simples'
      preLoaderRoute: typeof AppRelatorioDigitalizacaoCompressaoSimplesRouteImport
      parentRoute: typeof AppRelatorioDigitalizacaoRoute
    }
    '/_app/relatorio/digitalizacao/pendencias': {
      id: '/_app/relatorio/digitalizacao/pendencias'
      path: '/pendencias'
      fullPath: '/relatorio/digitalizacao/pendencias'
      preLoaderRoute: typeof AppRelatorioDigitalizacaoPendenciasRouteImport
      parentRoute: typeof AppRelatorioDigitalizacaoRoute
    }
    '/_app/relatorio/digitalizacao/perm-v': {
      id: '/_app/relatorio/digitalizacao/perm-v'
      path: '/perm-v'
      fullPath: '/relatorio/digitalizacao/perm-v'
      preLoaderRoute: typeof AppRelatorioDigitalizacaoPermVRouteImport
      parentRoute: typeof AppRelatorioDigitalizacaoRoute
    }
    '/_app/relatorio/especiais/': {
      id: '/_app/relatorio/especiais/'
      path: '/relatorio/especiais'
      fullPath: '/relatorio/especiais/'
      preLoaderRoute: typeof AppRelatorioEspeciaisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/especiais/$osNumero': {
      id: '/_app/relatorio/especiais/$osNumero'
      path: '/relatorio/especiais/$osNumero'
      fullPath: '/relatorio/especiais/$osNumero'
      preLoaderRoute: typeof AppRelatorioEspeciaisOsNumeroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/os/': {
      id: '/_app/relatorio/os/'
      path: '/relatorio/os'
      fullPath: '/relatorio/os/'
      preLoaderRoute: typeof AppRelatorioOsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/os/$osId/': {
      id: '/_app/relatorio/os/$osId/'
      path: '/relatorio/os/$osId'
      fullPath: '/relatorio/os/$osId/'
      preLoaderRoute: typeof AppRelatorioOsOsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/os/$osId/amostra/$amostraId/': {
      id: '/_app/relatorio/os/$osId/amostra/$amostraId/'
      path: '/relatorio/os/$osId/amostra/$amostraId'
      fullPath: '/relatorio/os/$osId/amostra/$amostraId/'
      preLoaderRoute: typeof AppRelatorioOsOsIdAmostraAmostraIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId': {
      id: '/_app/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId'
      path: '/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId'
      fullPath: '/relatorio/os/$osId/amostra/$amostraId/ensaio/$ensaioId'
      preLoaderRoute: typeof AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppChegadaAmostrasRouteChildren {
  AppChegadaAmostrasRegistroRoute: typeof AppChegadaAmostrasRegistroRoute
}

const AppChegadaAmostrasRouteChildren: AppChegadaAmostrasRouteChildren = {
  AppChegadaAmostrasRegistroRoute: AppChegadaAmostrasRegistroRoute,
}

const AppChegadaAmostrasRouteWithChildren =
  AppChegadaAmostrasRoute._addFileChildren(AppChegadaAmostrasRouteChildren)

interface AppRelatorioDigitalizacaoRouteChildren {
  AppRelatorioDigitalizacaoAdensamentoRoute: typeof AppRelatorioDigitalizacaoAdensamentoRoute
  AppRelatorioDigitalizacaoAsfDapRoute: typeof AppRelatorioDigitalizacaoAsfDapRoute
  AppRelatorioDigitalizacaoCapsulasRoute: typeof AppRelatorioDigitalizacaoCapsulasRoute
  AppRelatorioDigitalizacaoCompressaoSimplesRoute: typeof AppRelatorioDigitalizacaoCompressaoSimplesRoute
  AppRelatorioDigitalizacaoPendenciasRoute: typeof AppRelatorioDigitalizacaoPendenciasRoute
  AppRelatorioDigitalizacaoPermVRoute: typeof AppRelatorioDigitalizacaoPermVRoute
  AppRelatorioDigitalizacaoIndexRoute: typeof AppRelatorioDigitalizacaoIndexRoute
}

const AppRelatorioDigitalizacaoRouteChildren: AppRelatorioDigitalizacaoRouteChildren =
  {
    AppRelatorioDigitalizacaoAdensamentoRoute:
      AppRelatorioDigitalizacaoAdensamentoRoute,
    AppRelatorioDigitalizacaoAsfDapRoute: AppRelatorioDigitalizacaoAsfDapRoute,
    AppRelatorioDigitalizacaoCapsulasRoute:
      AppRelatorioDigitalizacaoCapsulasRoute,
    AppRelatorioDigitalizacaoCompressaoSimplesRoute:
      AppRelatorioDigitalizacaoCompressaoSimplesRoute,
    AppRelatorioDigitalizacaoPendenciasRoute:
      AppRelatorioDigitalizacaoPendenciasRoute,
    AppRelatorioDigitalizacaoPermVRoute: AppRelatorioDigitalizacaoPermVRoute,
    AppRelatorioDigitalizacaoIndexRoute: AppRelatorioDigitalizacaoIndexRoute,
  }

const AppRelatorioDigitalizacaoRouteWithChildren =
  AppRelatorioDigitalizacaoRoute._addFileChildren(
    AppRelatorioDigitalizacaoRouteChildren,
  )

interface AppRouteChildren {
  AppAnalisesRoute: typeof AppAnalisesRoute
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppCadastroRoute: typeof AppCadastroRoute
  AppCadastroDashboardRoute: typeof AppCadastroDashboardRoute
  AppChamadasRoute: typeof AppChamadasRoute
  AppChegadaAmostrasRoute: typeof AppChegadaAmostrasRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppEntregasRoute: typeof AppEntregasRoute
  AppEntreguesRoute: typeof AppEntreguesRoute
  AppGestaoRoute: typeof AppGestaoRoute
  AppOrdensServicoRoute: typeof AppOrdensServicoRoute
  AppOsAprovadas15dRoute: typeof AppOsAprovadas15dRoute
  AppPendentesRoute: typeof AppPendentesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSaturacaoRoute: typeof AppSaturacaoRoute
  AppAdminUsuariosRoute: typeof AppAdminUsuariosRoute
  AppModelosRelatoriosAdensamentoRoute: typeof AppModelosRelatoriosAdensamentoRoute
  AppModelosRelatoriosAsfDapRoute: typeof AppModelosRelatoriosAsfDapRoute
  AppModelosRelatoriosCisalhamentoDiretoRoute: typeof AppModelosRelatoriosCisalhamentoDiretoRoute
  AppModelosRelatoriosCompressaoSimplesRoute: typeof AppModelosRelatoriosCompressaoSimplesRoute
  AppModelosRelatoriosMespANaturalRoute: typeof AppModelosRelatoriosMespANaturalRoute
  AppModelosRelatoriosModuloResilienciaRoute: typeof AppModelosRelatoriosModuloResilienciaRoute
  AppModelosRelatoriosPermVRoute: typeof AppModelosRelatoriosPermVRoute
  AppModelosRelatoriosTriaxialCidRoute: typeof AppModelosRelatoriosTriaxialCidRoute
  AppModelosRelatoriosTriaxialCiuRoute: typeof AppModelosRelatoriosTriaxialCiuRoute
  AppModelosRelatoriosTriaxialUuRoute: typeof AppModelosRelatoriosTriaxialUuRoute
  AppModelosRelatoriosUmidadeNaturalRoute: typeof AppModelosRelatoriosUmidadeNaturalRoute
  AppProgramacaoCentralRoute: typeof AppProgramacaoCentralRoute
  AppProgramacaoCompatibilidadeRoute: typeof AppProgramacaoCompatibilidadeRoute
  AppProgramacaoDashboardRoute: typeof AppProgramacaoDashboardRoute
  AppProgramacaoEquipamentosRoute: typeof AppProgramacaoEquipamentosRoute
  AppProgramacaoGanttRoute: typeof AppProgramacaoGanttRoute
  AppProgramacaoScanRoute: typeof AppProgramacaoScanRoute
  AppProgramacaoTiposEnsaioRoute: typeof AppProgramacaoTiposEnsaioRoute
  AppRelatorioAdensamentoRoute: typeof AppRelatorioAdensamentoRoute
  AppRelatorioAsfDapRoute: typeof AppRelatorioAsfDapRoute
  AppRelatorioCisalhamentoDiretoRoute: typeof AppRelatorioCisalhamentoDiretoRoute
  AppRelatorioCompressaoSimplesRoute: typeof AppRelatorioCompressaoSimplesRoute
  AppRelatorioDigitalizacaoRoute: typeof AppRelatorioDigitalizacaoRouteWithChildren
  AppRelatorioEmissoesRoute: typeof AppRelatorioEmissoesRoute
  AppRelatorioMespARoute: typeof AppRelatorioMespARoute
  AppRelatorioMespANaturalRoute: typeof AppRelatorioMespANaturalRoute
  AppRelatorioModuloResilienciaRoute: typeof AppRelatorioModuloResilienciaRoute
  AppRelatorioPendentesRoute: typeof AppRelatorioPendentesRoute
  AppRelatorioPermVRoute: typeof AppRelatorioPermVRoute
  AppRelatorioTriaxialCidRoute: typeof AppRelatorioTriaxialCidRoute
  AppRelatorioUmidadeNaturalRoute: typeof AppRelatorioUmidadeNaturalRoute
  AppModelosRelatoriosIndexRoute: typeof AppModelosRelatoriosIndexRoute
  AppProgramacaoIndexRoute: typeof AppProgramacaoIndexRoute
  AppRelatorioIndexRoute: typeof AppRelatorioIndexRoute
  AppRelatorioEspeciaisOsNumeroRoute: typeof AppRelatorioEspeciaisOsNumeroRoute
  AppRelatorioEspeciaisIndexRoute: typeof AppRelatorioEspeciaisIndexRoute
  AppRelatorioOsIndexRoute: typeof AppRelatorioOsIndexRoute
  AppRelatorioOsOsIdIndexRoute: typeof AppRelatorioOsOsIdIndexRoute
  AppRelatorioOsOsIdAmostraAmostraIdIndexRoute: typeof AppRelatorioOsOsIdAmostraAmostraIdIndexRoute
  AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRoute: typeof AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalisesRoute: AppAnalisesRoute,
  AppAssistenteRoute: AppAssistenteRoute,
  AppCadastroRoute: AppCadastroRoute,
  AppCadastroDashboardRoute: AppCadastroDashboardRoute,
  AppChamadasRoute: AppChamadasRoute,
  AppChegadaAmostrasRoute: AppChegadaAmostrasRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppEntregasRoute: AppEntregasRoute,
  AppEntreguesRoute: AppEntreguesRoute,
  AppGestaoRoute: AppGestaoRoute,
  AppOrdensServicoRoute: AppOrdensServicoRoute,
  AppOsAprovadas15dRoute: AppOsAprovadas15dRoute,
  AppPendentesRoute: AppPendentesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSaturacaoRoute: AppSaturacaoRoute,
  AppAdminUsuariosRoute: AppAdminUsuariosRoute,
  AppModelosRelatoriosAdensamentoRoute: AppModelosRelatoriosAdensamentoRoute,
  AppModelosRelatoriosAsfDapRoute: AppModelosRelatoriosAsfDapRoute,
  AppModelosRelatoriosCisalhamentoDiretoRoute:
    AppModelosRelatoriosCisalhamentoDiretoRoute,
  AppModelosRelatoriosCompressaoSimplesRoute:
    AppModelosRelatoriosCompressaoSimplesRoute,
  AppModelosRelatoriosMespANaturalRoute: AppModelosRelatoriosMespANaturalRoute,
  AppModelosRelatoriosModuloResilienciaRoute:
    AppModelosRelatoriosModuloResilienciaRoute,
  AppModelosRelatoriosPermVRoute: AppModelosRelatoriosPermVRoute,
  AppModelosRelatoriosTriaxialCidRoute: AppModelosRelatoriosTriaxialCidRoute,
  AppModelosRelatoriosTriaxialCiuRoute: AppModelosRelatoriosTriaxialCiuRoute,
  AppModelosRelatoriosTriaxialUuRoute: AppModelosRelatoriosTriaxialUuRoute,
  AppModelosRelatoriosUmidadeNaturalRoute:
    AppModelosRelatoriosUmidadeNaturalRoute,
  AppProgramacaoCentralRoute: AppProgramacaoCentralRoute,
  AppProgramacaoCompatibilidadeRoute: AppProgramacaoCompatibilidadeRoute,
  AppProgramacaoDashboardRoute: AppProgramacaoDashboardRoute,
  AppProgramacaoEquipamentosRoute: AppProgramacaoEquipamentosRoute,
  AppProgramacaoGanttRoute: AppProgramacaoGanttRoute,
  AppProgramacaoScanRoute: AppProgramacaoScanRoute,
  AppProgramacaoTiposEnsaioRoute: AppProgramacaoTiposEnsaioRoute,
  AppRelatorioAdensamentoRoute: AppRelatorioAdensamentoRoute,
  AppRelatorioAsfDapRoute: AppRelatorioAsfDapRoute,
  AppRelatorioCisalhamentoDiretoRoute: AppRelatorioCisalhamentoDiretoRoute,
  AppRelatorioCompressaoSimplesRoute: AppRelatorioCompressaoSimplesRoute,
  AppRelatorioDigitalizacaoRoute: AppRelatorioDigitalizacaoRouteWithChildren,
  AppRelatorioEmissoesRoute: AppRelatorioEmissoesRoute,
  AppRelatorioMespARoute: AppRelatorioMespARoute,
  AppRelatorioMespANaturalRoute: AppRelatorioMespANaturalRoute,
  AppRelatorioModuloResilienciaRoute: AppRelatorioModuloResilienciaRoute,
  AppRelatorioPendentesRoute: AppRelatorioPendentesRoute,
  AppRelatorioPermVRoute: AppRelatorioPermVRoute,
  AppRelatorioTriaxialCidRoute: AppRelatorioTriaxialCidRoute,
  AppRelatorioUmidadeNaturalRoute: AppRelatorioUmidadeNaturalRoute,
  AppModelosRelatoriosIndexRoute: AppModelosRelatoriosIndexRoute,
  AppProgramacaoIndexRoute: AppProgramacaoIndexRoute,
  AppRelatorioIndexRoute: AppRelatorioIndexRoute,
  AppRelatorioEspeciaisOsNumeroRoute: AppRelatorioEspeciaisOsNumeroRoute,
  AppRelatorioEspeciaisIndexRoute: AppRelatorioEspeciaisIndexRoute,
  AppRelatorioOsIndexRoute: AppRelatorioOsIndexRoute,
  AppRelatorioOsOsIdIndexRoute: AppRelatorioOsOsIdIndexRoute,
  AppRelatorioOsOsIdAmostraAmostraIdIndexRoute:
    AppRelatorioOsOsIdAmostraAmostraIdIndexRoute,
  AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRoute:
    AppRelatorioOsOsIdAmostraAmostraIdEnsaioEnsaioIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminMigrarLabstateRoute: AdminMigrarLabstateRoute,
  AuthRoute: AuthRoute,
  PendenteRoute: PendenteRoute,
  RegistroAmostraRoute: RegistroAmostraRoute,
  RegistroChegadaRoute: RegistroChegadaRoute,
  ApiPhotoFileIdRoute: ApiPhotoFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
